- name: copying the mongo repo file to yum repository
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

- name: install the mongodb component
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: enable and start the service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: enable the remote connection
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: restart the service
  ansible.builtin.service:
    name: mongod
    state: restarted
