- name: Setup the node environment
  ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

- name: install the nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

  