- name: copying the service file
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: "/etc/systemd/system/{{component}}.service"

- name: Reload the service
  ansible.builtin.systemd:
    daemon_reload: true

- name: enable and start the service
  ansible.builtin.service:
    name: "{{component}}"
    state: started
    enabled: yes

- name: Restart the service
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    