CATALOGUE_HOST: catalogue.suhaildevops.online
USER_HOST: user.suhaildevops.online
CART_HOST: cart.suhaildevops.online
SHIPPING_HOST: shipping.suhaildevops.online
PAYMENT_HOST: payment.suhaildevops.online


